---

    - name: Configure Iptables
      become: true
      tags: install
      ignore_errors: yes
      shell: |
        set -x
        # Publishing
        if [ {{ compute.0.replicas }} -ne 0 ]
        then
          API_VIP={{ ocp_api_vip }}
          APPS_VIP={{ ocp_apps_vip }}
        else
          API_VIP={{ ocp_api_vip }}
          APPS_VIP={{ ocp_api_vip }}
        fi
        if [ {{ lb }} == "true" ]
        then
          API_VIP={{ ocp_cluster_net_gw }}
          APPS_VIP={{ ocp_cluster_net_gw }}
        fi
        iptables -I FORWARD 1 -i any -o any -j ACCEPT
        iptables -I PREROUTING 1 -t nat -i {{ kvm_interface }} -p tcp --dport 6443 -j DNAT --to $API_VIP:6443
        iptables -I FORWARD 1 -p tcp -d $API_VIP --dport 6443 -j ACCEPT
        iptables -I PREROUTING 1 -t nat -i {{ kvm_interface }} -p tcp --dport 443 -j DNAT --to $APPS_VIP:443
        iptables -I FORWARD 1 -p tcp -d $APPS_VIP --dport 443 -j ACCEPT
        iptables -I PREROUTING 1  -t nat -i {{ kvm_interface }} -p tcp --dport 80 -j DNAT --to $APPS_VIP:80
        iptables -I FORWARD 1 -p tcp -d $APPS_VIP --dport 80 -j ACCEPT
        iptables -I INPUT 1 -p tcp  --dport 6443 -j ACCEPT
        iptables -I INPUT 1 -p tcp  --dport 443 -j ACCEPT
        iptables -I INPUT 1 -p tcp  --dport 80 -j ACCEPT
        iptables-save > /etc/iptables.conf
      when: kvm_firewall == "iptables"


